# Generated by Django 5.1.1 on 2024-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strawberry', '0002_alter_measurement_water_ec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('gh1_ec_be', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh1_ec_mid', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh1_ec_end', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh1_ph_be', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh1_ph_mid', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh1_ph_end', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh1_ml_be', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh1_ml_mid', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh1_ml_end', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh2_ec_be', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh2_ec_mid', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh2_ec_end', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh2_ph_be', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh2_ph_mid', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh2_ph_end', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh2_ml_be', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh2_ml_mid', models.FloatField(blank=True, default=0.0, null=True)),
                ('gh2_ml_end', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
